### ISSUE TITLE
Skycat 3.13 from ESO

### ISSUE THREAD

**Issue by olebole** [Starlink/skycat#4]
Hi,

there is a new version of Skycat available on ESO: `ftp://ftp.eso.org/usg/skycat/skycat-3.1.3.tar.gz` (dated April 2018).

It would be good to have both versions somehow in sync...

Best

Ole

**Comment by olebole** [comment]
As a followup: I just checked the contents of 3.13 vs. the [3.12 import](https://github.com/Starlink/skycat/tree/037c74a0ab3f81a28517221404d975f031c19301): The changes are identical to #3; obviously ESO just also included that patch for their new version.

So, just the version number could be pushed ... :-)

**Comment by pwdraper** [comment]
Merged 3.1.4 so closing.
